// <auto-generated />
namespace Whapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LocationFieldsToProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationFieldsToProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111948139_LocationFieldsToProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
